### ISSUE TITLE
android 7.0及以上 获得句柄为null解决了吗

### ISSUE THREAD

**Issue by e-jlion** [Dovar66/mm_demo#2]
android 7.0 系统能给个支持吗？
我 调试发现android 7.0下的微信在红包弹出来的界面上getRootInActiveWindow() 获得句柄方法为null 导致不会拆开红包问题，能帮忙解答怎么处理吗

**Comment by Dovar66** [comment]
我今天用小米6调试也遇到了这个问题，不过暂时还没找到有效的解决方法

**Comment by Dovar66** [comment]
@a312586670 我这两天用小米6调试也发现了这个问题，不过暂时还没找到有效的解决方法，等解决了我再@你

**Comment by e-jlion** [comment]
你好，android 7.0系统 问题你解决了吗？解决了告诉我下

**Comment by e-jlion** [comment]
或者给一个QQ，我们QQ上交流讨论下怎么处理

**Comment by e-jlion** [comment]
你好，我已经解决了

**Comment by yeshengwu** [comment]
@a312586670 怎么解决的？方便说下么。

**Comment by Dovar66** [comment]
@a312586670 可否提交一下代码我参考下，谢谢？

**Comment by Dovar66** [comment]
@a312586670 可否提交一下代码方便我参考下？谢谢

**Comment by redblue47** [comment]
@Dovar66 @a312586670 大神们请问是如何解决这个问题的？谢谢

**Comment by redblue47** [comment]
@Dovar66 请问这个问题有解决吗？太奇怪了

**Comment by zgmd** [comment]
我也有这个问题，但是不是每次都出现，我用的是三星S8+  Android8.0,有一个奇怪的问题，就是最后的开红包的Button按钮的id获取了，在s8上就报错，找不到这个buuuton，在华为mete-2上就可以正常操作，微信版本是一致的，求解
